apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: doplace
  namespace: doplace
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`place.polydo.dev`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: backend
          port: 8000
    - match: Host(`place.polydo.dev`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: frontend
          port: 8001
  tls:
    secretName: cloudflare-origin-cert
