apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - do-cument.yaml
  - doplace.yaml
  - keepalived.yaml
  - kube-prometheus-stack.yaml
  - minecraft.yaml
  - uptime-kuma.yaml
